package cn.xtits.icode.entity;

import java.io.Serializable;
import java.util.Date;

public class Project implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.PackageName
     *
     * @mbg.generated
     */
    private String packageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.SqlType
     *
     * @mbg.generated
     */
    private Integer sqlType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.DbHost
     *
     * @mbg.generated
     */
    private String dbHost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.DbName
     *
     * @mbg.generated
     */
    private String dbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.DbUser
     *
     * @mbg.generated
     */
    private String dbUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.DbPassword
     *
     * @mbg.generated
     */
    private String dbPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.MakeBillMan
     *
     * @mbg.generated
     */
    private String makeBillMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.CreateDate
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ModifyDate
     *
     * @mbg.generated
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.DeleteFlag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Id
     *
     * @return the value of project.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Id
     *
     * @param id the value for project.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Code
     *
     * @return the value of project.Code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Code
     *
     * @param code the value for project.Code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Name
     *
     * @return the value of project.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Name
     *
     * @param name the value for project.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.PackageName
     *
     * @return the value of project.PackageName
     *
     * @mbg.generated
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.PackageName
     *
     * @param packageName the value for project.PackageName
     *
     * @mbg.generated
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.SqlType
     *
     * @return the value of project.SqlType
     *
     * @mbg.generated
     */
    public Integer getSqlType() {
        return sqlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.SqlType
     *
     * @param sqlType the value for project.SqlType
     *
     * @mbg.generated
     */
    public void setSqlType(Integer sqlType) {
        this.sqlType = sqlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.DbHost
     *
     * @return the value of project.DbHost
     *
     * @mbg.generated
     */
    public String getDbHost() {
        return dbHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.DbHost
     *
     * @param dbHost the value for project.DbHost
     *
     * @mbg.generated
     */
    public void setDbHost(String dbHost) {
        this.dbHost = dbHost == null ? null : dbHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.DbName
     *
     * @return the value of project.DbName
     *
     * @mbg.generated
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.DbName
     *
     * @param dbName the value for project.DbName
     *
     * @mbg.generated
     */
    public void setDbName(String dbName) {
        this.dbName = dbName == null ? null : dbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.DbUser
     *
     * @return the value of project.DbUser
     *
     * @mbg.generated
     */
    public String getDbUser() {
        return dbUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.DbUser
     *
     * @param dbUser the value for project.DbUser
     *
     * @mbg.generated
     */
    public void setDbUser(String dbUser) {
        this.dbUser = dbUser == null ? null : dbUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.DbPassword
     *
     * @return the value of project.DbPassword
     *
     * @mbg.generated
     */
    public String getDbPassword() {
        return dbPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.DbPassword
     *
     * @param dbPassword the value for project.DbPassword
     *
     * @mbg.generated
     */
    public void setDbPassword(String dbPassword) {
        this.dbPassword = dbPassword == null ? null : dbPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.MakeBillMan
     *
     * @return the value of project.MakeBillMan
     *
     * @mbg.generated
     */
    public String getMakeBillMan() {
        return makeBillMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.MakeBillMan
     *
     * @param makeBillMan the value for project.MakeBillMan
     *
     * @mbg.generated
     */
    public void setMakeBillMan(String makeBillMan) {
        this.makeBillMan = makeBillMan == null ? null : makeBillMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.CreateDate
     *
     * @return the value of project.CreateDate
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.CreateDate
     *
     * @param createDate the value for project.CreateDate
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Modifier
     *
     * @return the value of project.Modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Modifier
     *
     * @param modifier the value for project.Modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ModifyDate
     *
     * @return the value of project.ModifyDate
     *
     * @mbg.generated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ModifyDate
     *
     * @param modifyDate the value for project.ModifyDate
     *
     * @mbg.generated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.DeleteFlag
     *
     * @return the value of project.DeleteFlag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.DeleteFlag
     *
     * @param deleteFlag the value for project.DeleteFlag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}