package cn.xtits.icode.entity;

import java.io.Serializable;
import java.util.Date;

public class Schemata implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schemata.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schemata.Code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schemata.MakeBillMan
     *
     * @mbg.generated
     */
    private String makeBillMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schemata.CreateDate
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schemata.ModifyDate
     *
     * @mbg.generated
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schemata.Modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schemata.DeleteFlag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schemata
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schemata.Id
     *
     * @return the value of schemata.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schemata.Id
     *
     * @param id the value for schemata.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schemata.Code
     *
     * @return the value of schemata.Code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schemata.Code
     *
     * @param code the value for schemata.Code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schemata.MakeBillMan
     *
     * @return the value of schemata.MakeBillMan
     *
     * @mbg.generated
     */
    public String getMakeBillMan() {
        return makeBillMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schemata.MakeBillMan
     *
     * @param makeBillMan the value for schemata.MakeBillMan
     *
     * @mbg.generated
     */
    public void setMakeBillMan(String makeBillMan) {
        this.makeBillMan = makeBillMan == null ? null : makeBillMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schemata.CreateDate
     *
     * @return the value of schemata.CreateDate
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schemata.CreateDate
     *
     * @param createDate the value for schemata.CreateDate
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schemata.ModifyDate
     *
     * @return the value of schemata.ModifyDate
     *
     * @mbg.generated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schemata.ModifyDate
     *
     * @param modifyDate the value for schemata.ModifyDate
     *
     * @mbg.generated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schemata.Modifier
     *
     * @return the value of schemata.Modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schemata.Modifier
     *
     * @param modifier the value for schemata.Modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schemata.DeleteFlag
     *
     * @return the value of schemata.DeleteFlag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schemata.DeleteFlag
     *
     * @param deleteFlag the value for schemata.DeleteFlag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}