package cn.xtits.icode.mapper;

import cn.xtits.icode.entity.ConnectionInfo;
import cn.xtits.icode.entity.ConnectionInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConnectionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connectioninfo
     *
     * @mbg.generated
     */
    long countByExample(ConnectionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connectioninfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connectioninfo
     *
     * @mbg.generated
     */
    int insert(ConnectionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connectioninfo
     *
     * @mbg.generated
     */
    int insertSelective(ConnectionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connectioninfo
     *
     * @mbg.generated
     */
    List<ConnectionInfo> selectByExample(ConnectionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connectioninfo
     *
     * @mbg.generated
     */
    ConnectionInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connectioninfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConnectionInfo record, @Param("example") ConnectionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connectioninfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConnectionInfo record, @Param("example") ConnectionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connectioninfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConnectionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connectioninfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConnectionInfo record);
}