package cn.xtits.icode.mapper;

import cn.xtits.icode.entity.Schemata;
import cn.xtits.icode.entity.SchemataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchemataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemata
     *
     * @mbg.generated
     */
    long countByExample(SchemataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemata
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemata
     *
     * @mbg.generated
     */
    int insert(Schemata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemata
     *
     * @mbg.generated
     */
    int insertSelective(Schemata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemata
     *
     * @mbg.generated
     */
    List<Schemata> selectByExample(SchemataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemata
     *
     * @mbg.generated
     */
    Schemata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemata
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Schemata record, @Param("example") SchemataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemata
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Schemata record, @Param("example") SchemataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemata
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Schemata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemata
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Schemata record);
}