package cn.xtits.icode.mapper;

import cn.xtits.icode.entity.TableInfo;
import cn.xtits.icode.entity.TableInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbg.generated
     */
    long countByExample(TableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbg.generated
     */
    int insert(TableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbg.generated
     */
    int insertSelective(TableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbg.generated
     */
    List<TableInfo> selectByExample(TableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbg.generated
     */
    TableInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TableInfo record, @Param("example") TableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TableInfo record, @Param("example") TableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TableInfo record);
}