server:
  context-path: /icode-api
spring:
  datasource:
    url: jdbc:mysql://119.37.194.4:11161/icode?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: '!QQ1234567890-=q'
    driver-class-name: com.mysql.jdbc.Driver
  #取消模板文件缓存
  thymeleaf:
    cache: false
  #设置文件大小
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
#
APP_TOKEN: IUzIwMTUyN1NiJ9NDkDkUciOiJeyJG1O1cGhd
TTL_MILLIS: 864000000
PROJECT_PATH: O:\icode\mes
TEMPLATE_PATH: O:\testsvn
TEMPLATE_SVN: http://119.37.194.4:11151/svn/mes/icode/trunk/java/icode-core/template
SVN_USER: ShengHaiJiang
SVN_PWD: 123456
logging:
  level: debug
